In [1]:
import pandas as pd
import numpy as np

In [2]:
mnar_toy_dataset = pd.read_csv(r"C:\Users\potat\Downloads\mimic-lstm-master\mimic-lstm-master\data\toy_datasets\mnar_toy_data.csv")
mar_toy_dataset = pd.read_csv(r"C:\Users\potat\Downloads\mimic-lstm-master\mimic-lstm-master\data\toy_datasets\mar_toy_data.csv")
mcar_toy_dataset = pd.read_csv(r"C:\Users\potat\Downloads\mimic-lstm-master\mimic-lstm-master\data\toy_datasets\mcar_toy_data.csv")


ground_truth = pd.read_csv(r"C:\Users\potat\Downloads\mimic-lstm-master\mimic-lstm-master\data\toy_datasets\ground_truth.csv")


array([235111], dtype=int64)

In [21]:
def find_missingness(data = mnar_toy_dataset):
    cols = len(data.iloc[:,1:].iloc[0])
    rows = len(data.iloc[:,1:])
    length = cols*rows

    missingness = sum(np.reshape(data.iloc[:,1:].isna().applymap(lambda x : 0 if x == False else 1).values,(-1,1))) / length
    return missingness

In [22]:
find_missingness()

array([0.235111])

In [23]:
find_missingness(mar_toy_dataset)

array([0.085462])

In [24]:
find_missingness(mcar_toy_dataset )

array([0.199584])